---
title: "flat_study-the-squirrels.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(glue)

primary_fur_color <- "Blue"
message(glue("We will focus on {primary_fur_color} squirrels"))
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_message_fur_color
    
```{r function-get_message_fur_color}

#' G a message with the fur color of interest.
#'
#' @param primary_fur_color a character string. 
#' @importFrom glue glue
#'
#' @return Nothing. Used for side effect. Outputs a message in the console.
#' 
#' @export
#' 
#' @examples
get_message_fur_color <- function(primary_fur_color){
   message(glue("We will focus on {primary_fur_color} squirrels")) 
}
```
  
```{r example-get_message_fur_color}
get_message_fur_color(primary_fur_color = "Black")
get_message_fur_color(primary_fur_color = "White")
get_message_fur_color(primary_fur_color = "Green")
```
  
```{r tests-get_message_fur_color}
test_that("get_message_fur_color works", {
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Black"),
    regexp = "We will focus on Black squirrels"
  )
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_study_squirrels.Rmd", vignette_name = "Study the squirrels")
```
