# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand


test_that("check_squirrel_data_integrity works", {
  expect_true(inherits(check_squirrel_data_integrity, "function")) 
})

test_that("check_squirrel_data_integrity works",
          {
  expect_message(
    object= check_squirrel_data_integrity(dataset = data_act_squirrels),
    regexp = "Everything is correct,  start analyse!"
  )
          }
)

the_data_bad <- data_act_squirrels 
the_data_bad<- dplyr::rename(the_data_bad, secondary_color = primary_fur_color )

the_data_very_bad <- data_act_squirrels
the_data_very_bad[["primary_fur_color"]][3] <- "violet"

test_that("check_squirrel_data_integrity works",
          {
  expect_error(
    object= check_squirrel_data_integrity(dataset = the_data_bad),
    regexp = "Primary fur color is not present in the dataset"
  )
          }
)



test_that("check_squirrel_data_integrity works",
          {
  expect_error(
    object= check_squirrel_data_integrity(dataset = the_data_very_bad),
    regexp = "One or more color of the string color are not valid primary fur color"
  )
          }
)

