# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_data works", {
  expect_equal(check_data( c("Gray", "Gray", "Black")),c("Gray", "Gray", "Black"))
 })
 
 test_that("check_data error message works", {
   expect_error(
    object = check_data(c("Gray", "Gray","Brown")),
    regexp = "One or more color of the string color are not valid primary fur color")
  })

