# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_primary_color_is_ok works", {
  expect_equal(check_primary_color_is_ok( c("Gray", "Gray", "Black")),c("Gray", "Gray", "Black"))
 })
 
 test_that("check_primary_color_is_ok error message works", {
   expect_error(
    object = check_primary_color_is_ok(c("Gray", "Gray","Brown")),
    regexp = "One or more color of the string color are not valid primary fur color")
  })

