# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

#' check_squirrel_data_integrity
#' 
#' Description The function checks that the data contains a primary_fur_color column, and that this column contains only allowed colors 
#' 
#' @param dataset A dataset.
#' @return a message if everything is OK
#' 
#' @export

#' @examples
#' check_squirrel_data_integrity(dataset = data_act_squirrels)
#' 
#' # create dummy data 
#' #the_data_bad <- data_act_squirrels 
#' #the_data_bad<- dplyr::rename(the_data_bad, secondary_color = primary_fur_color )
#' #check_squirrel_data_integrity(dataset = the_data_bad)
#' 
#' 
check_squirrel_data_integrity <- function(dataset){
  
  if (any(colnames(dataset)== "primary_fur_color"))
 {
    
  vector_to_test <-   dataset[["primary_fur_color"]]
    
  if(all(
   vector_to_test %in% c("Gray", "Cinnamon", "Black", NA)
  ))
 {
   message(
     "Everything is correct,  start analyse!")}
 else{
    stop("One or more color of the string color are not valid primary fur color")
  }
    
 }
  
 else {
  stop("Primary fur color is not present in the dataset")
}
  
}



