# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand


#' check_primary_color_is_ok
#'
#' @return all_colors_OK: a character vector or error message 
#' @param   string : a character vector. The color of the squirrels.
#' 
#' @export
#'
#' @examples
#' check_data( c("Gray", "Gray", "Black"))
#' #check_data( c("Gray", "Gray","Brown"))
check_data <- function(string) {
  if(
    all(
    string %in% c("Gray", "Cinnamon", "Black", NA)
  ))
  {all_colors_OK <- string
  return(all_colors_OK)
  }
   else{ stop("One or more color of the string color are not valid primary fur color")
   }

}

