# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand


#' G a message with the fur color of interest.
#'
#' @param primary_fur_color a character string. 
#' @importFrom glue glue
#'
#' @return Nothing. Used for side effect. Outputs a message in the console.
#' 
#' @export
#' 
#' @examples
#' get_message_fur_color(primary_fur_color = "Black")
#' get_message_fur_color(primary_fur_color = "White")
#' get_message_fur_color(primary_fur_color = "Green")
get_message_fur_color <- function(primary_fur_color){
   message(glue("We will focus on {primary_fur_color} squirrels")) 
}
